# Generated by Django 3.0.8 on 2020-08-25 00:10

from django.db import migrations, models
import django.db.models.deletion
import tema.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliders', models.CharField(choices=[('1 Slider', 1), ('2 Sliders', 2), ('3 Sliders', 3)], default=2, max_length=9)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Personalização',
                'verbose_name_plural': 'Personalizações',
            },
        ),
        migrations.CreateModel(
            name='SlidersOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tema.Sliders')),
            ],
            options={
                'verbose_name': 'Ordenação Sliders',
                'verbose_name_plural': 'Ordenação Sliders',
            },
        ),
    ]
