# Generated by Django 3.0.8 on 2020-08-25 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidersorder',
            name='sliders',
        ),
        migrations.AddField(
            model_name='sliders',
            name='slidersTema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tema.Tema'),
        ),
        migrations.AddField(
            model_name='slidersorder',
            name='slidersOrderTema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tema.Tema'),
        ),
    ]
