# Generated by Django 3.0.8 on 2020-08-25 02:00

import categorias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0002_auto_20200824_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidersorder',
            name='slidersOrderTema',
        ),
        migrations.AddField(
            model_name='tema',
            name='sliders',
            field=models.CharField(choices=[('1', categorias.models.Category)], default=0, max_length=10),
        ),
        migrations.DeleteModel(
            name='Sliders',
        ),
        migrations.DeleteModel(
            name='SlidersOrder',
        ),
    ]
