# Generated by Django 3.0.8 on 2020-08-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('tema', '0005_auto_20200825_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='slider_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Category'),
        ),
    ]
