# Generated by Django 3.0.8 on 2020-08-26 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('tema', '0006_auto_20200825_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='slider_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slider_2', to='categorias.Category'),
        ),
        migrations.AddField(
            model_name='tema',
            name='slider_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slider_3', to='categorias.Category'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='slider_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slider_1', to='categorias.Category'),
        ),
    ]
