# Generated by Django 3.0.8 on 2020-09-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0007_auto_20200825_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='nome_do_layout',
            field=models.CharField(default='Layout 1', max_length=128),
        ),
    ]
