# Generated by Django 3.0.8 on 2020-09-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0008_tema_nome_do_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='nome_do_layout',
            field=models.CharField(max_length=128),
        ),
    ]
