# Generated by Django 3.0.8 on 2020-09-01 00:55

from django.db import migrations, models
import tema.models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0009_auto_20200831_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=tema.models.Logo.upload_callback)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
    ]
